name: Jest CI

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 15  # You can adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install
    
    - name: Lint with ESLint
      run: npm run lint

    - name: Format with Prettier 
      run: npm run prettier

    - name: Test with Jest
      env:
        CI: true  # Set the CI environment variable
      run: npm run test

    - name: Build stage 
      run: npm run build

  deploy-to-devel:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Replace with your desired AWS region

      - name: Build and push Docker image
        run: |
          # Log in to Amazon ECR
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com

          # Build and tag your Docker image
          docker build -t app-repo:latest .

          # Tag the image with the ECR repository URI
          docker tag app-repo:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/app-repo:latest

          # Push the image to ECR
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/app-repo:latest

      - name: Update ECS task definition
        run: |
          # Create a new revision for the ECS task definition
          aws ecs register-task-definition \
            --region us-west-2 \
            --family app-first-task \
            --container-definitions "$(cat ecs-container-definition.json)"

          # Update the ECS service with the new task definition
          aws ecs update-service \
            --region us-west-2 \
            --cluster app-cluster \
            --service app-first-service \
            --task-definition app-first-task:3  
  